services:
  - type: web
    name: wedding-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false  # Будет задаваться вручную
      - key: ADMIN_CHAT_ID
        sync: false  # ID чата для уведомлений (например, -1001234567890)
      - key: PORT
        value: 10000
