services:
  - type: web
    name: wedding-site-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py  # ← ИЗМЕНИТЬ ТУТ!
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8496935356:AAF3UOHTXykrqK6-nOeVFpAPCtewst-02PA
      - key: ADMIN_CHAT_ID
        value: "787419978"
      - key: PORT
        value: "10000"
