services:
  - type: web
    name: wedding-site-bot-anna
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: "8496935356:AAF3UOHTXykrqK6-nOeVFpAPCtewst-02PA"
      - key: ADMIN_CHAT_ID
        value: "787419978"
      - key: GROUP_CHAT_ID
        value: "-5275786758"
    plan: free
    autoDeploy: true
